# Generated by Django 4.0.2 on 2023-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(choices=[('AI & Robotics', 'AI & Robotics'), ('Business Analysis', 'Business Analysis'), ('Business Intelligence & Data Analytics', 'Business Intelligence & Data Analytics'), ('Business Transformation & Change', 'Business Transformation & Change'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Design & Architecture', 'Design & Architecture'), ('Cyber Security', 'Cyber Security'), ('Digital, UX & UI design', 'Digital, UX & UI design'), ('ERP & CRM', 'ERP & CRM'), ('IT Support & Systems Administration', 'IT Support & Systems Administration'), ('Project Management', 'Project Management'), ('Software Development, Testing & Engineering', 'Software Development, Testing & Engineering')], default='NN', max_length=50),
        ),
    ]
