# Generated by Django 4.0.2 on 2023-03-27 10:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI & Robotics', 'AI & Robotics'), ('Business Analysis', 'Business Analysis'), ('Business Intelligence & Data Analytics', 'Business Intelligence & Data Analytics'), ('Business Transformation & Change', 'Business Transformation & Change'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Design & Architecture', 'Design & Architecture'), ('Cyber Security', 'Cyber Security'), ('Digital, UX & UI design', 'Digital, UX & UI design'), ('ERP & CRM', 'ERP & CRM'), ('IT Support & Systems Administration', 'IT Support & Systems Administration'), ('Project Management', 'Project Management'), ('Software Development, Testing & Engineering', 'Software Development, Testing & Engineering')], default=1, max_length=288),
            preserve_default=False,
        ),
    ]
