# Generated by Django 4.0.2 on 2023-03-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_interest_alter_customuser_skills'),
        ('users', '0007_alter_customuser_interest_alter_customuser_skills'),
    ]

    operations = [
    ]
