# Generated by Django 4.0.2 on 2023-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponser',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
