# Generated by Django 4.0.2 on 2023-04-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_sponser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
